#!/bin/sh

PROG=`basename $0`

if [ $# != 1 ] ; then
   echo  "Usage: $PROG <toptic>"
   exit 1
fi
TOPIC=$1

/opt/confluent/bin/kafka-topics --zookeeper localhost:2181 --if-not-exists --create --topic $TOPIC  --partitions 1 --replication-factor 1

